### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by hongyaz** [Lan-lab/SIGNET#2]
Thank you for the cool software! 
I'm hoping to use this tool, and could you share the package versions that you used, e.g. for pytorch, scanpy, sklearn, etc? And also the Python version would be useful too!
Thanks again!

**Comment by xlan** [comment]
Qinhuan,

Could you please share the information? Thank you,

Best,

Xun

**Comment by luoqh17** [comment]
scanpy        --1.7.2
scikit-learn  --0.23.2
torch            --1.5.0+cpu
numpy          --1.19.5              
pandas         --1.1.5
torchvision    --0.6.0+cpu

**Comment by luoqh17** [comment]
sorry, I did not share the version of packages,tutorial was also upadated.
Thanks for your suggestions!

**Comment by luoqh17** [comment]
python --3.6.13
